import type { Person } from "@prisma/client";
import { type NextPage } from "next";
import Head from "next/head";



import PersonDetail from "../components/PersonDetail";


const Home: NextPage = () => {

  const changeId = (x:number) =>{
    sessionStorage.setItem('id',x.toString())
    window.location.href='/person_id'
  }
  return (
    <>
      <Head>
        <title>Heritage</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="flex min-h-screen flex-col items-center ">
        <button onClick={()=>changeId(1)}>1</button>
      </main>
    </>
  );
};

export default Home;
